-- WORKING WITH MULTIPLE TABLES

USE CURSO_SQL2014_IMPL
GO

-- BEFORE YOU KNOW HOW TO WORK WITH MULTIPLE TABLES
-- YOU MUST UNDERSTAND HOW THEY ARE RELATED

-- SEE FIGURE1_DIAGRAM.JPG
-- NOTE THE PARENT-CHILD RELATIONSHIP BETWEEN SOME TABLES

-- LET'S SEE A SIMPLE RELATIONSHIP BETWEEN THE TABLES
-- PEDIDOS, ITENS_PEDIDO, PRODUTOS AND CATEGORIAS

-- SEE FIGURE2_EXAMPLE.JPG

-- LET'S SEE HOW WE RELATE ITENS_PEDIDO AND PRODUTOS
-- BUT BEFORE THAT, LET'S SEE THE SINTAX FOR THE SELECT AGAIN:

/* 
SELECT <COLUMNS>
FROM <TABLES>
[WHERE <FILTERS>]
[ORDER BY <COLUMNS]

*/

-- IN THE <TABLES> CLAUSE YOU CAN USE ALIASES JUST 
-- LIKE IN THE COLUNS

SELECT ...
FROM TABLE1 AS X, TABLE2 AS Y
...

-- AFTER USING THE TABLES INSIDE THE FROM CLAUSE
-- YOU NEED TO SPECIFY THE COLUMNS OF THE RELATIONSHIP

-- YOU CAN USE MORE THAN ON TABLE IN THE SELECT
-- THOUGH JOINS. THEARE ARE SOME JOIN TYPES BUT
-- LET'S SEE THE EQÜIJOIN FIRST

-- YOU DO THAT IN TWO WAYS:

	-- 1) THE ANSI WAY (RECOMMENDED)
	--  USE THE  ... JOIN... ON... CLAUSES
	
	SELECT * 
	FROM ITENS_PEDIDO I 
	     INNER JOIN
		 PRODUTOS P
    ON 	I.IDPRODUTO = P.IDPRODUTO

	-- 2) THE NON-ANSI WAY
	-- USE THE WHERE CLAUSE
	SELECT * 
	FROM  ITENS_PEDIDO I, PRODUTOS P
    WHERE I.IDPRODUTO = P.IDPRODUTO

-- YOU CAN SPECIFY THE COLUMNS USING THE <TABLE>.<COLUMN> SYNTAX
	SELECT I.IDPEDIDO
	      ,I.IDPRODUTO
		  ,P.IDPRODUTO
		  ,P.NomeProduto
	FROM ITENS_PEDIDO I 
	     INNER JOIN
		 PRODUTOS P
    ON 	I.IDPRODUTO = P.IDPRODUTO

-- NOS LET'S SEE THE JOIN OF THE PEDIDOS AND ITENS_PEDIDO TABLES

	SELECT PE.IDPEDIDO
	      ,PE.DATAPEDIDO
		  ,I.IdPedido
		  ,I.IdProduto
		  ,I.QtdPedida
	FROM PEDIDOS PE 
	     INNER JOIN
		 ITENS_PEDIDO I
    ON 	PE.IDPEDIDO = I.IDPEDIDO

-- ANOTHER EXAMPLE: JOIN BETWEEN PRODUTOS AND CATEGORIAS

SELECT PRO.IDPRODUTO
      ,PRO.NomeProduto
	  ,PRO.IdCategoria
	  ,C.IdCategoria
	  ,C.NomeCategoria
FROM PRODUTOS PRO INNER JOIN CATEGORIAS C
     ON PRO.IdCategoria = C.IdCategoria
ORDER BY C.NomeCategoria, PRO.NomeProduto

-- WE CAN JOIN MORE THAN 2 TABLES USING THE INNER JOIN
-- LET'S JOIN PEDIDOS, ITENS_PEDIDO AND PRODUTOS TOGHETER

	SELECT PE.IDPEDIDO
	      ,PE.DATAPEDIDO
		  ,I.IdPedido
		  ,I.IdProduto
		  ,PRO.NomeProduto
		  ,PRO.PrcProducto
		  ,I.QtdPedida
	FROM PEDIDOS PE 
		INNER JOIN ITENS_PEDIDO I
			ON 	PE.IDPEDIDO = I.IDPEDIDO
	    INNER JOIN PRODUTOS PRO
		    ON I.IdProduto = PRO.IdProduto

-- THERE ARE OTHER RELATIONSHIPS LIKE THESE IN THE DIAGRAM