-- VIEWS
----------------------------------------

USE CURSO_SQL2014_IMPL
GO

-- VIEWS ARE PRE-STORED SELECT STATEMENTS
--- THEY HAVE MANY ADVANTAGES:
--	-> ENCAPSULATE COMPLEX LOGIC
--  -> SIMPLIFY PERMISSION MANAGEMENT
--  -> OPTIMIZE PERFORMANCE (WITH INDEXES ON VIEWS)

-- VIEWS ARE DATABASE OBJECTS 
-- CHECK THE VIEWS FOLDER ON OBJECT EXPLORER

-- THEARE ARE SYSTEM VIEWS AND USER VIEWS
-- SYSTEM VIEWS SHOW IMPORTANT SYSTEM INFORMATION
-- FROM INTERNAL OBJECTS

SELECT *
FROM SYS.all_objects


SELECT *
FROM SYS.all_columns

-- THERE ARE ALSO THE DMV: DYNAMIC MANAGEMENT VIEWS
-- EXAMPLE:

SELECT *
FROM SYS.dm_db_file_space_usage

-- BASIC SYNTAX TO CREATE A VIEW:

CREATE VIEW <view_name> AS
<select_statement>

-- NOTE: THERE ARE MORE OPTIONS FOR THE CREATE VIEW SYNTAX

-- VIEWS ARE USED JUST LIKE TABLES. EXAMPLE:

CREATE VIEW VW_CUSTOMERS
AS 
SELECT *
FROM CLIENTES

select 1 + 1

SELECT *
FROM VW_CUSTOMERS

-- NOTE: YOU ALWAYS HAVE TO NAME ALL YOUR COLUMNS
-- TO CREATE A VIEW!

-- QUICK CHECK THE SOURCE SELECT OF A VIEW 
-- WITH THE SP_HELPTEXT <view_name> PROCEDURE

SP_HELPTEXT VW_CUSTOMERS

-- YOU CAN CHANGE THE VIEW (ALTER VIEW) AND REMOVE IT (DROP VIEW)

ALTER VIEW VW_CUSTOMERS
AS
SELECT *
FROM CLIENTES
WHERE NomeCliente LIKE '%a'

SELECT * 
FROM VW_CUSTOMERS

DROP VIEW VW_CUSTOMERS

SELECT * 
FROM VW_CUSTOMERS

-- YOU CAN ALSO CREATE VIEWS FROM THE OBJECT EXPLORER UI

-- THEARE ARE A FEW EXCEPTIONS, BUT MOST SELECT CLAUSES
-- CAN BE USED ON A VIEW. EXAMPLES:
--	-> YOU 	CAN'T HAVE A VIEW WITH A SELF-REFERENCE
--  -> YOU CAN'T HAVE THE ORDER BY IN A VIEW WITHOUT A TOP CLAUSE

-- VIEW CAN BE USED WITH INSERT, UPDATE AND DELETE
-- JUST MAKE SURE YOUR VIEW HAVE ALL THE COLUMNS
-- EXAMPLE:

CREATE TABLE TVIEW
(
	ID TINYINT,
	NAME VARCHAR(100)
)
GO

CREATE VIEW VW_TVIEW
AS
SELECT * FROM TVIEW

INSERT VW_TVIEW VALUES(1,'A')
INSERT VW_TVIEW VALUES(2,'B')
INSERT VW_TVIEW VALUES(3,'C')

SELECT * FROM TVIEW
SELECT * FROM VW_TVIEW

UPDATE VW_TVIEW
SET ID = 22
WHERE ID = 2

SELECT * FROM TVIEW
SELECT * FROM VW_TVIEW

DELETE VW_TVIEW
WHERE ID =22

DROP TABLE TVIEW
DROP VIEW VW_TVIEW




