-- TRANSACTIONS, LOCK, BLOCK AND DEADLOCK
-- CONNECTION 1
-----------------------------------------

CREATE DATABASE DB_LOCK
GO

-- USING THE DATABASE
USE DB_LOCK
GO

-- CHECK THE PROCESS ID
SELECT @@SPID

-- CREATING THE TEST TABLE
CREATE TABLE TB_LOCK
(
	ID INT PRIMARY KEY,
	NAME VARCHAR(20)
)

-- INSERTING SOME DATA
INSERT TB_LOCK VALUES(1,'A')
INSERT TB_LOCK VALUES(2,'B')
INSERT TB_LOCK VALUES(3,'C')
INSERT TB_LOCK VALUES(4,'D')

-- CHECK THE DATA
SELECT *
FROM TB_LOCK

-- CHECK THE LOCKS
SP_LOCK 53

-- OPEN TRANSACTIONS
SELECT @@TRANCOUNT

-- BEGING THE TRANSACTION
BEGIN TRANSACTION
	
	-- UPDATE ONLY ONE ROW
	UPDATE TB_LOCK 
	SET NAME = 'Y'
	WHERE ID = 1

	UPDATE TB_LOCK 
	SET NAME = 'Z'
	WHERE ID = 2

-- CANCEL THE TRANSACTION
ROLLBACK
COMMIT
-- COMMIT THE TRANSACTION
COMMIT

-- UPDATE ANOTHER LINE
UPDATE TB_LOCK
SET NAME = 'X'
WHERE ID = 2

