-- TRANSACTIONS, LOCK, BLOCK AND DEADLOCK
-- CONNECTION 2
-----------------------------------------
-- USING THE DATABASE
USE DB_LOCK

-- CHECK THE PROCESS ID
SELECT @@SPID

-- CHECK THE DATA
SELECT *
FROM TB_LOCK
where ID > 1


-- GET JUST ONE ROW
SELECT * 
FROM TB_LOCK
WHERE ID = 4

-- CHANGING THE TIMEOUT FOR THIS SESSION
SET LOCK_TIMEOUT -1
SET LOCK_TIMEOUT 5000


-- CHECK THE LOCKS
SP_LOCK 53

-- SEE THE NUMBER OF OPEN TRANSACTIONS
SELECT @@TRANCOUNT

-- BEGIN A NEW TRANSACTION
BEGIN TRANSACTION

	-- UPDATE ON ONLY ONE ROW
	UPDATE TB_LOCK
	SET NAME = 'Y'
	WHERE ID = 2

	UPDATE TB_LOCK
	SET NAME = 'A'
	WHERE ID = 1

	-- UPDATE ANOTHER ROW
	UPDATE TB_LOCK
	SET NAME = 'Y'
	WHERE ID = 1

-- CANCEL THE TRANSAÇÃO
ROLLBACK 