-- INSERTING DATA
----------------------------------------

USE CURSO_SQL2014_IMPL
GO

-- THE BASIC COMMAND TO PUT DATA INSIDE SQL SERVER IS THE INSERT COMMAND
-- NO MATTER WHAT TOO YOU USE, AN INSERT IS ALL THAT SQL SERVER UNDERSTAND

-- BASIC SYNTAX:

-- INSERT <table> VALUES(<columns>)

-- YOU NEED TO VERIFY ALL THE CONSTRAINTS (PK, FK, NULL, ETC)

-- EXAMPLES:

CREATE TABLE T1
(
	COL1 INT NOT NULL PRIMARY KEY,
	COL2 VARCHAR(10)
)
GO

-- SIMPLE INSERT (WITHOUT THE COLUMN'S NAMES)
INSERT T1 VALUES(1,'A')
GO

INSERT T1 VALUES(NULL,'A')
GO

SELECT * FROM T1

-- INSERT WITH THE COLUMNS NAMES:

INSERT T1(COL1,COL2) VALUES(2,'B')
GO

SELECT * FROM T1

INSERT INTO T1 VALUES(4,NULL)

SELECT * FROM T1

-- NOTE: IF YOU DO NOT PROVIDE A COLUMN NAME, THE DEFAULT (IF EXISTS)
-- WILL BE USED. YOU MAY USE THE DEFAULT KEYWORD

-- YOU MAY USE THE INSERT WITH THE SELECT STATEMENT
-- MAKE SURE ALL THE COLUMNS AND DATATYPES MATCH

SELECT TOP 10 IDCLIENTE
            , NOMECLIENTE
FROM CLIENTES

INSERT T1
SELECT TOP 10 IDCLIENTE
            , SUBSTRING(NOMECLIENTE,1,10)
FROM CLIENTES

SELECT * FROM T1

-- YOU CAN ALSO USE THE INTO KEYWORD ON THE SELECT STATEMENT
-- TO CREATE A TABLE A INSERT THE DATA. 
-- MAKE SURE YOU HAVE ALL THE COLUMN'S NAMES
-- EXAMPLE:

SELECT TOP 10 IDCLIENTE
            , NOMECLIENTE
FROM CLIENTES


SELECT TOP 10 IDCLIENTE
            , NOMECLIENTE
INTO MY_NEW_TABLE
FROM CLIENTES


SELECT *
FROM MY_NEW_TABLE

-- NOTE: DO NOT MIX THE INTO KEYWORD OF THE INSERT WITH THE INTO ON THE SELECT!
-- EXAMPLE:


INSERT INTO T1 VALUES(3,'C')

-- TIPS: DON'T FORGET TO ERASE THE TABLES CREATED WITH INTO (DATA SPACE)
--       ONLY THE COLUMNS WILL BE CREATED (NO CONSTRAINTS OR INDEXES)
--       IF THE SELECT DO NOT RETURN ANY ROWS, ONLY THE STRUCTURE WILL BE CREATED
--       EXAMPLE:

SELECT TOP 0 IDCLIENTE
            , NOMECLIENTE
INTO MY_OTHER_NEW_TABLE
FROM CLIENTES


SELECT *
FROM MY_OTHER_NEW_TABLE

-- MOST OF THE TIME YOU DON'T EXPECT THAT AN INSERT RETURN ROWS
-- IT JUST RETURN THE NUMBER OF ROWS INSERTED OR AN ERROR (CHECK ON THE APPLICATION)
-- HOWEVER, IT MAY RETURN ROWS WITH A TRIGGER (WILL SEE IT LATTER ON)

-- ALWAYS KEEP IN MIND THAT INSERTS MAY NEED A SEQUENCE TO BE PERFORMED
-- CHECK THE PK/FK ON THE MODEL
-- YOU CAN ALSO DISABLE THE CONSTRATINS, INSERT, AND THEN ENABLE THEM

-- FOR MANY INSERTS (IMPORT TASKS) ALWAYS CHECK THE TRANSACTION LOG SIZE 