-- SQL SERVER PROCESSES
---------------------------------------------------------------------------

USE CURSO_SQL2014_IMPL
GO

-- EACH CONNECTION IS LINKED TO A INTERNAL SQL SERVER PROCESS
-- NOTE: THESE PROCESSES ARE INSIDE THE SQL SERVER PROCESS ON THE OS

-- YOU CAN SEE THE CONNECTION ID USING @@SPID

SELECT @@SPID

-- PROCESS BELOW 50 ARE INTERNAL TO SQL SERVER
-- YOU CAN SEE ALL THE PROCESSES USING SP_WHO OR SP_WHO2

EXEC SP_WHO

EXEC SP_WHO 53

EXEC SP_WHO2

-- ALSO, CHECK THE 'PROCESSES' OPTION UNDER THE ACTIVITY MONITOR

-- YOU CAN SEE THE EXACT SQL COMMAND BEING EXECUTED ON THE COMMAND COLUMNS

-- MOST OF THE TIME YOU MONITOR THE PROCESSES TO SEE BLOCKS AND LOCKS
-- JOBS ALSO HAVE PROCESS 
-- YOU CAN OBTAIN VALUABLE INFORMATION ABOUT IT:
	--> THE APP, LOGIN AND THE DATABASE
	--> THE SQL STATEMENT
	--> THE WAIT TIME
	--> THE WAIT RESOURCE

-- TO CANCEL A PROCESS USE THE KILL <SP_ID> COMMAND
-- YOU NEED ADMINISTRATOR PRIVLEDGES
-- BE CAREFULL: THE APP. MAY DO NOT KNOW HOW TO HANDLE IT

KILL 53

-- USE KILL ONLY ON EXTREME CASES. AND BE AWARE OF LONG TRANSACTIONS
-- A MESSAGE IS POST ON SQL SERVER LOG WHEN A PROCESS IS KILLED