-- MERGING DATA
----------------------------------------

USE CURSO_SQL2014_IMPL
GO

-- SOMETIMES YOU WANT TO SYNCHRONIZE TABLES, I.E. MAKE THEN HAVE THE SAME ROWS
-- IT IS VERY CUMBERSOME DO THIS WITH INSERTS, UPDATES AND DELETES
-- YOU CAN USE THE MERGE COMMAND. BASIC SYNTAX:

-- MERGE <table_target> AS <alias1>
-- USING <table_source> AS <alias2>
-- ON <comparison_exp>
-- WHEN [MATCHED|NOT MATCHED] THEN <SQL>;

-- NEED: 1) SOURCE AND TARGET TABLE
--       2) COLUMN TO COMPARE
--       3) WHAT TO DO WHEN THERE IS AND THERE ISN'T A MATCH

-- NOTE: ALWAYS FINISH THE MERGE STATEMENT WITH A SEMI-COLON (;)

-- SIMPLE EXAMPLE: PRODUCTS AND UPDATED PRODUCTS        


--CREATE A TARGET TABLE
CREATE TABLE PRODUCTS
(
	PRODUCTID INT PRIMARY KEY,
	PRODUCTNAME VARCHAR(100),
	RATE MONEY
) 
GO


--INSERT RECORDS INTO TARGET TABLE
INSERT INTO PRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 30.00),
(4, 'BISCUIT', 40.00)
GO



--CREATE SOURCE TABLE
CREATE TABLE UPDATEDPRODUCTS
(
	PRODUCTID INT PRIMARY KEY,
	PRODUCTNAME VARCHAR(100),
	RATE MONEY
) 
GO

--INSERT RECORDS INTO SOURCE TABLE
INSERT INTO UPDATEDPRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 25.00),
(3, 'MUFFIN', 35.00),
(4, 'BISCUIT', 60.00)
GO

SELECT * FROM PRODUCTS
SELECT * FROM UPDATEDPRODUCTS
GO

-- NOW LET'S SYNCRONIZE THE DATA ON THE PRODUCTS TABLE
-- JUST UPDATE THE VALUES IF THERE IS A MATCH


MERGE PRODUCTS		  AS TARGET
USING UPDATEDPRODUCTS AS SOURCE 
ON (TARGET.PRODUCTID = SOURCE.PRODUCTID) 

WHEN MATCHED THEN 
		UPDATE SET TARGET.RATE = SOURCE.RATE; 
GO

SELECT * FROM PRODUCTS
SELECT * FROM UPDATEDPRODUCTS
GO


-- WHAT IF YOU HAVE A NEW PRODUCT ON THE UPDATEDPRODUCTS TABLE? 
-- YOU HAVE TO INSERT IT ON THE PRODUCTS TABLE

TRUNCATE TABLE PRODUCTS
TRUNCATE TABLE UPDATEDPRODUCTS

INSERT INTO PRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 30.00),
(4, 'BISCUIT', 40.00)
GO


INSERT INTO UPDATEDPRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 25.00),
(5, 'BOLHACA', 55.00)
GO

SELECT * FROM PRODUCTS
SELECT * FROM UPDATEDPRODUCTS
GO

-- NOW LET'S REWRITE THE MERGE USING THE WHEN NOT MATCHED BY TARGET CLAUSE

MERGE PRODUCTS		  AS TARGET
USING UPDATEDPRODUCTS AS SOURCE 
ON (TARGET.PRODUCTID = SOURCE.PRODUCTID) 

WHEN MATCHED THEN 
		UPDATE SET TARGET.RATE = SOURCE.RATE

WHEN NOT MATCHED BY TARGET THEN 
	INSERT (PRODUCTID, PRODUCTNAME, RATE) 
	VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.RATE);
GO

-- WHAT IF YOU DELETE A PRODUCT ON THE UPDATEDPRODUCTS TABLE AND WANT THE SYNCRONIZATION? 
-- YOU HAVE TO DELETE IT ON THE PRODUCTS TABLE

TRUNCATE TABLE PRODUCTS
TRUNCATE TABLE UPDATEDPRODUCTS

INSERT INTO PRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 30.00),
(4, 'BISCUIT', 40.00)
GO


INSERT INTO UPDATEDPRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 30.00)
GO

SELECT * FROM PRODUCTS
SELECT * FROM UPDATEDPRODUCTS
GO

-- LET'S ADD THE 'WHEN NOT MATCHED BY SOURCE THEN' CLAUSE

MERGE PRODUCTS		  AS TARGET
USING UPDATEDPRODUCTS AS SOURCE 
ON (TARGET.PRODUCTID = SOURCE.PRODUCTID) 

WHEN MATCHED THEN 
		UPDATE SET TARGET.RATE = SOURCE.RATE

WHEN NOT MATCHED BY TARGET THEN 
	INSERT (PRODUCTID, PRODUCTNAME, RATE) 
	VALUES (SOURCE.PRODUCTID, SOURCE.PRODUCTNAME, SOURCE.RATE)

WHEN NOT MATCHED BY SOURCE THEN 
DELETE;

GO

-- FINALLY, YOU CAN USE THE OUTPUT CLAUSE TO CHECK THE MODIFICATIONS
-- YOU HAVE THE $action INTERNAL VARIABLE 
-- THAT GIVES YOU THE MODIFICATION (INSERT, UPDATE OR DELETE)

-- EXAMPLE: MERGE THE VALUES

TRUNCATE TABLE PRODUCTS
TRUNCATE TABLE UPDATEDPRODUCTS

INSERT INTO PRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 30.00)
GO


INSERT INTO UPDATEDPRODUCTS
VALUES
(1, 'TEA', 10.00),
(2, 'COFFEE', 20.00),
(3, 'MUFFIN', 99.00)
GO

SELECT * FROM PRODUCTS
SELECT * FROM UPDATEDPRODUCTS
GO

MERGE PRODUCTS		  AS TARGET
USING UPDATEDPRODUCTS AS SOURCE 
ON (TARGET.PRODUCTID = SOURCE.PRODUCTID) 

WHEN MATCHED THEN 
		UPDATE SET TARGET.RATE = SOURCE.RATE

OUTPUT $action, 
DELETED.PRODUCTID AS TARGETPRODUCTID, 
DELETED.PRODUCTNAME AS TARGETPRODUCTNAME, 
DELETED.RATE AS TARGETRATE, 
INSERTED.PRODUCTID AS SOURCEPRODUCTID, 
INSERTED.PRODUCTNAME AS SOURCEPRODUCTNAME, 
INSERTED.RATE AS SOURCERATE; 


GO
