-- STORED PROCEDURES
-----------------------------------------

USE CURSO_SQL2014_IMPL
GO

--> STORED PROCEDURES ARE ONE OF THE OLDEST FEATURES IN SQL SERVER

--> USED TO IMPLEMENT BUSSINESS RULES IN THE DATABASE
--> HAS ADVANTAGES AND DISADVANTAGES

--> A SIMPLE EXAMPLE:

CREATE PROCEDURE HELLO_WORLD
AS
BEGIN
  SELECT 'HELLO WORLD'
END
GO

HELLO_WORLD

EXECUTE HELLO_WORLD

exec HELLO_WORLD
GO

-- TO SEE THE SOURCE CODE OF THE PROCEDURE

SP_HELPTEXT HELLO_WORLD
GO

-->A STORED PROCEDURE CAN BE ENCRYPTED

CREATE PROCEDURE ST_ENCRYPTED
WITH ENCRYPTION
AS
BEGIN
  SELECT 'HELLO WORLD'
END
GO

EXEC ST_ENCRYPTED
GO

SP_HELPTEXT ST_ENCRYPTED
GO

--> STORED PROCEDURE CAN RETURN MORE THAN ONE VALUE

CREATE PROCEDURE ST_RET_VALUES
AS
BEGIN
  SELECT COUNT(*) FROM sysobjects
  SELECT COUNT(*) FROM sysindexes
END
GO

EXEC ST_RET_VALUES
GO

--> AN EXAMPLE WITH PARAMETERS
CREATE PROCEDURE ST_CALC  @X INT , @Y INT OUTPUT
AS
BEGIN
	SET @Y = @X * 2
END
GO

-- RUNNING THE EXAMPLE

DECLARE @RESULT INT

-- EXEC ST_CALC 10,@RESULT OUTPUT
EXEC ST_CALC 20,@RESULT OUTPUT

SELECT @RESULT

--> STORED PROCEDURES CAN BE USED TO POPULATE TABLES

CREATE PROCEDURE ST_INSERT_TABLE
AS
BEGIN
  SELECT GETDATE()
END
GO

CREATE TABLE TB_DATE
(
  COL1 DATETIME
)
GO

exec ST_INSERT_TABLE

SELECT * FROM TB_DATE

INSERT TB_DATE
EXEC ST_INSERT_TABLE

SELECT * FROM TB_DATE

--> STORED PROCEDURE CAN RECEIVE PARAMETERS USED 
--  IN QUERIES
DROP PROCEDURE ST_GET_OBJECTS_ALL
GO

SELECT TOP 10 *
FROM sysobjects

CREATE PROCEDURE ST_GET_OBJECTS_ALL
	@OBJECTID INT,
	@NAME VARCHAR(100),
	@START_DATE DATETIME,
	@END_DATE   DATETIME
AS
BEGIN
	IF @OBJECTID IS NOT NULL
		SELECT *
		FROM sysobjects
		WHERE id = @OBJECTID

	IF @NAME IS NOT NULL
		SELECT *
		FROM sysobjects
		WHERE name = @NAME


	IF ( (@START_DATE IS NOT NULL) AND
	     (@END_DATE IS NOT NULL) )
	
		SELECT *
		FROM sysobjects
		WHERE crdate BETWEEN @START_DATE AND @END_DATE

END

-- TESTS
EXEC ST_GET_OBJECTS_ALL 5,NULL,NULL,NULL

EXEC ST_GET_OBJECTS_ALL NULL,'syspriorities',NULL,NULL

EXEC ST_GET_OBJECTS_ALL NULL
                       ,NULL
                       ,'2014-01-01'
                       ,'2014-05-30'
                       



--> STORED PROCEDURES CAN ALSO CREATE DYNAMIC STATEMENTS

DROP PROCEDURE ST_TEST_DIN
GO

create PROCEDURE ST_TEST_DIN @PAR_1 nvarchar(100)
AS
BEGIN
	declare @SQL_STATEMENT NVARCHAR(100)

	SET @SQL_STATEMENT = N'SELECT '	+ @PAR_1 
	EXEC sp_executesql @SQL_STATEMENT  
	
END

EXEC ST_TEST_DIN 1

EXEC ST_TEST_DIN 'getdate()'

EXEC ST_TEST_DIN '1+1'

EXEC ST_TEST_DIN 'abc'

EXEC ST_TEST_DIN '''abc'''
