-- SQL SERVER FUNCTIONS

-- EACH DATABASE HAS IT'S OWN SET OF FUNCTIONS
-- THEY CAN BE USED IN DIFFERENT WAYS
-- LET'S LEARN HOW TO USE THEN
-- TIP: ALWAYS CHECK THE DOCUMENTATION!

-- TEXT FUNCTIONS

-- UPPER()

SELECT idProduto
      ,NomeProduto
	  ,upper(NomeProduto) as 'BIG' 
FROM PRODUTOS
WHERE UPPer(NomeProduto) LIKE 'CAIXA%'

-- SUBSTRING()

SELECT ENDCLIENTE,
	   SUBSTRING(ENDCLIENTE,1,15) AS ENDERECO
FROM CLIENTES

-- LEN()

SELECT NomeCliente
      ,len(NomeCliente) as 'SIZE' 
FROM CLIENTES

-- MANY MANY OTHERS. CHECK THE DOCUMENTATION

-- NUMERICAL FUNCTIONS

-- ROUND()

SELECT IDPRODUTO	'Produto'
      , PrcProducto 'Preco' 
	  ,PrcProducto/2 as 'No round' 
	  ,round(PrcProducto/2,1) as 'Dec. Round' 
FROM PRODUTOS

-- RAND()

SELECT RAND()

-- DATATYPE CONVERTION FUNCTIONS

-- SIMPLE CONVERT()

SELECT CONVERT(INT,'10')

SELECT CONVERT(INT,'10.9')

SELECT CONVERT(float,'10.9')

SELECT CONVERT(VARCHAR(4),'10.123')

SELECT GETDATE() AS 'DATE' 
      , CONVERT(VARCHAR,GETDATE()) 'CONVERTED DATE' 

-- YOU CAN CHOOSE THE DATE FORMAT WHEN CONVERTING
-- USE THE 3RD PARAMETER OF CONVERT()

SELECT IdPedido
      ,DataPedido 
	  ,convert(char(10),DataPedido, 103)  as 'Time' 
FROM PEDIDOS

-- TO GET JUST THE TIME
SELECT IdPedido
      ,DataPedido 
	  ,convert(char(5),DataPedido, 108)  as 'Time' 
FROM PEDIDOS

-- YOU CAN ADD AND SUBTRACT NUMBERS FROM DATES
-- THE UNIT USED WILL BE SECONDS

SELECT GETDATE()      AS 'DATE' 
      ,GETDATE() + 1  AS 'DATE+1' 
	  ,GETDATE() - 1  AS 'DATE-1' 

-- YOU ALSO HAVE THE DATEADD() FUNCTION TO 
-- WORK WITH OTHER PARTS (YEAR, MONTH, HOUR, MINUTE, ETC)
-- CHECK THE DOCUMENTATION FOR THE CORRECT SYNTAX

SELECT IDPEDIDO
      ,DATAPEDIDO
	  ,DATEADD(month,1,DataPedido) as 'NextMonth' 
	  ,DATEADD(hour,-1,DataPedido) as 'PreviousHour' 
FROM PEDIDOS

-- TO GET DATE INTERVALS: DATEDIFF()

SELECT GETDATE()      AS 'NOW'
      ,GETDATE() + 1  AS 'NEXT DAY' 
	  ,DATEDIFF(DAY,GETDATE(), GETDATE() + 1) AS 'DIFF_IN_DAYS' 
	  ,DATEDIFF(HOUR,GETDATE(), GETDATE() + 1) AS 'DIFF_IN_HOURS' 
	  ,DATEDIFF(SECOND,GETDATE(), GETDATE() + 1) AS 'DIFF_IN_SECONDS' 

